service: serverless-es6-boilerplate

custom:
  profiles:
    local: local
    # dev: 51
    # test: profile-test
    # prod: profile-prod
  environment:
    default_env: &default_env
      SERVERLESS_SERVICE: ${self:service}
      SERVERLESS_STAGE: ${self:provider.stage}
      SERVERLESS_VERSION: ${file(./package.json):version}
      SERVERLESS_REGION: ${opt:region, self:provider.region}
    dev:
      <<: *default_env
      stage: dev
    prod:
      <<: *default_env
      stage: prod

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-1'} # Overwrite the default region used. Default is us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  logRetentionInDays: 30 # Set the default RetentionInDays for a CloudWatch LogGroup
  environment: ${self:custom.environment.${self:provider.stage}}

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - src/**


functions:
  apiRequest:
    handler: handler.request
    events:
      - http:
          # Health check
          path: /
          method: get
          cors: true
      - http:
          # Example function throwing error
          path: /error
          method: get
          cors: true
      - http:
          # Example function returning promise
          path: /promise
          method: get
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

resources:
  Resources:
    HealthCheckLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 1
